// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tb8MEnBWnzayPvWA8hTqtJAZ5YOAoaQ',
    appId: '1:721304936218:web:f9122a4607402f4fe1d6a3',
    messagingSenderId: '721304936218',
    projectId: 'habitheroproject',
    authDomain: 'habitheroproject.firebaseapp.com',
    storageBucket: 'habitheroproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnySg7XGqJkr1H9iHwNJjiuvW-wIbyUI',
    appId: '1:721304936218:android:091713c1591e33a7e1d6a3',
    messagingSenderId: '721304936218',
    projectId: 'habitheroproject',
    storageBucket: 'habitheroproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Ahxerpoc3rtSLsnctVNGFzBx7dGRHSw',
    appId: '1:721304936218:ios:5ad893fa98b06115e1d6a3',
    messagingSenderId: '721304936218',
    projectId: 'habitheroproject',
    storageBucket: 'habitheroproject.appspot.com',
    androidClientId: '721304936218-9o9b1o3kmeimsbgpqsptih2elesghbsu.apps.googleusercontent.com',
    iosClientId: '721304936218-v975toimng1vc7igh52j2fld71frv98d.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Ahxerpoc3rtSLsnctVNGFzBx7dGRHSw',
    appId: '1:721304936218:ios:6edaf21497f38b12e1d6a3',
    messagingSenderId: '721304936218',
    projectId: 'habitheroproject',
    storageBucket: 'habitheroproject.appspot.com',
    androidClientId: '721304936218-9o9b1o3kmeimsbgpqsptih2elesghbsu.apps.googleusercontent.com',
    iosClientId: '721304936218-pn59esonqshbrvoio5htobfod5unb7de.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitHero.RunnerTests',
  );
}
